// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoClassificados.Infra.Data.Contexts;

namespace ProjetoClassificados.Infra.Data.Migrations
{
    [DbContext(typeof(ProjetoClassificadosContext))]
    partial class ProjetoClassificadosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Anuncio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DateTime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("IdAnuncio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagem")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Preco")
                        .HasMaxLength(24)
                        .HasColumnType("float(24)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Interesse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAnuncio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("anuncioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("usuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("anuncioId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Interesses");
                });

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Anuncio", b =>
                {
                    b.HasOne("ProjetoClassificados.Dominio.Entidades.Usuario", null)
                        .WithMany("Anuncios")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Interesse", b =>
                {
                    b.HasOne("ProjetoClassificados.Dominio.Entidades.Anuncio", "anuncio")
                        .WithMany("Inteesses")
                        .HasForeignKey("anuncioId");

                    b.HasOne("ProjetoClassificados.Dominio.Entidades.Usuario", "usuario")
                        .WithMany("Inteesses")
                        .HasForeignKey("usuarioId");

                    b.Navigation("anuncio");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Anuncio", b =>
                {
                    b.Navigation("Inteesses");
                });

            modelBuilder.Entity("ProjetoClassificados.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("Inteesses");
                });
#pragma warning restore 612, 618
        }
    }
}
